apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: volv
        mountPath: /data
      - name: volv2
        mountPath: /data2
    ports:
      - containerPort: 80
  volumes:
    - name: volv
      persistentVolumeClaim:
        claimName: local-path-pvc
    - name: volv2
      persistentVolumeClaim:
        claimName: another-pvc
