{{- range $name, $pvc := .Values.pvcs }}
{{- if $pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
spec:
  accessModes:
    - {{ .accessMode | default $.Values.defaults.accessMode }}
  resources:
    requests:
      storage: {{ required "pvcs.size is required" $pvc.size }}
  storageClassName: {{ $pvc.storageClassName | default ( $pvc.autoDelete | ternary $.Values.defaults.storageClassNameAutoDelete $.Values.defaults.storageClassName ) }}
---
{{- end }}
{{- end }}