{{- if and .Values.enabled .Values.preset.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.preset.name | default (printf "%s-preset-cnp" (coalesce .Values.nameOverride .Values.global.nameOverride .Release.Name)) }}
spec:
  {{- if .Values.preset.endpointSelector }}
  endpointSelector: {{ toYaml .Values.preset.endpointSelector | nindent 4 }}
  {{- else if .Values.preset.useChartEndpointSelector }}
  endpointSelector:
    matchLabels:
      {{- include "ju-common.selectorLabels" . | nindent 6 }}
  {{- else }}
  endpointSelector: {}
  {{- end }}
  {{- if not .Values.preset.ingress.unrestricted }}
  ingress:
    {{- if .Values.preset.ingress.none }}
    - {}
    {{- else }}
    {{- if .Values.preset.namespaceIsolation }}
    - fromEndpoints:
        - {}
    {{- end }}
    {{- if .Values.preset.ingress.fromNamespace }}
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: {{ .Values.preset.ingress.fromNamespace }}
    {{- end }}
    {{- if .Values.preset.ingress.fromNamespaces }}
    - fromEndpoints:
        {{- range .Values.preset.ingress.fromNamespaces }}
        - matchLabels:
            io.kubernetes.pod.namespace: {{ . }}
        {{- end }}
    {{- end }}
    {{- if .Values.preset.ingress.fromCluster }}
    - fromEntities:
        - cluster
    {{- end }}
    {{- if .Values.preset.ingress.fromWorld }}
    - fromEntities:
        - world
    {{- end }}
    {{- if .Values.preset.ingress.fromKubeApi }}
    - fromEntities:
        - kube-apiserver
        {{- if .Values.defaults.extendedKubeApiIngressRule }}
        - host
        - remote-node
        {{- end }}
    {{- end }}
    {{- if .Values.preset.ingress.fromLocalSubnet }}
    - fromCIDR:
        - {{ .Values.defaults.localSubnetCidr }}
    {{- end }}
    {{- if .Values.preset.ingress.fromIngressController }}
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: {{ .Values.defaults.ingressControllerNamespace }}
    {{- end }}
    {{- range $fromNetworkLabel := .Values.preset.ingress.fromNetworkLabels }}
      {{- if kindIs "string" $fromNetworkLabel }}
        {{- $fromNetworkLabel = dict "label" $fromNetworkLabel }}
      {{- end }}
    - fromEndpoints:
        - matchLabels:
            {{ $fromNetworkLabel.label }}: {{ $.Values.defaults.toNetworkLabelValue | quote }}
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists
      {{- if $fromNetworkLabel.ports }}
      toPorts:
        - ports:
            {{- range $port := $fromNetworkLabel.ports }}
            - port: {{ $port | quote }}
            {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.preset.ingress.fromExternalIngressController }}
    - fromEndpoints:
        - matchLabels:
            {{ .Values.defaults.customExternalIngressNetworkLabel }}: {{ $.Values.defaults.toNetworkLabelValue | quote }}
            {{- if .Values.defaults.externalIngressControllerNamespace }}
            io.kubernetes.pod.namespace: {{ .Values.defaults.externalIngressControllerNamespace }}
            {{- end }}
    {{- if and (not (kindIs "bool" .Values.preset.ingress.fromExternalIngressController)) .Values.preset.ingress.fromExternalIngressController.ports }}
      toPorts:
        - ports:
            {{- range $port := .Values.preset.ingress.fromExternalIngressController.ports }}
            - port: {{ $port | quote }}
            {{- end }}
    {{- end }}
    {{- end }}
    {{- range .Values.preset.ingress.rules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if not .Values.preset.egress.unrestricted }}
  egress:
    {{- if .Values.preset.egress.none }}
    - {}
    {{- else }}
    {{- if .Values.preset.namespaceIsolation }}
    - toEndpoints:
        - {}
    {{- end }}
    {{- if .Values.preset.egress.toNamespace }}
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: {{ .Values.preset.egress.toNamespace }}
    {{- end }}
    {{- if .Values.preset.egress.toNamespaces }}
    - toEndpoints:
        {{- range .Values.preset.egress.toNamespaces }}
        - matchLabels:
            io.kubernetes.pod.namespace: {{ . }}
        {{- end }}
    {{- end }}
    {{- if .Values.preset.egress.toCluster }}
    - toEntities:
        - cluster
    {{- end }}
    {{- if .Values.preset.egress.toWorld }}
    - toEntities:
        - world
    {{- end }}
    {{- if .Values.preset.egress.toLocalSubnet }}
    - toCIDR:
        - {{ .Values.defaults.localSubnetCidr }}
    {{- end }}
    {{- if .Values.preset.egress.toKubeApi }}
    - toEntities:
        - kube-apiserver
    {{- end }}
    {{- if .Values.preset.egress.toKubeDns }}
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    {{- end }}
    {{- if .Values.preset.egress.toFQDNs }}
    - toFQDNs:
        {{- range .Values.preset.egress.toFQDNs }}
        - matchName: {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- if .Values.preset.egress.toDefaultPostgresDb }}
    - toEndpoints:
        - matchLabels:
            {{ .Values.defaults.defaultPostgresDbNetworkLabel }}: {{ .Values.defaults.fromNetworkLabelValue | quote }}
            {{- if .Values.defaults.defaultPostgresDbNamespace }}
            io.kubernetes.pod.namespace: {{ .Values.defaults.defaultPostgresDbNamespace }}
            {{- end }}
      {{- if .Values.defaults.defaultPostgresDbPort }}
      toPorts:
        - ports:
            - port: {{ .Values.defaults.defaultPostgresDbPort | quote }}
      {{- end }}
    {{- end }}
    {{- range $toNetworkLabel := .Values.preset.egress.toNetworkLabels }}
      {{- if kindIs "string" $toNetworkLabel }}
        {{- $toNetworkLabel = dict "label" $toNetworkLabel }}
      {{- end }}
    - toEndpoints:
        - matchLabels:
            {{ $toNetworkLabel.label }}: {{ $.Values.defaults.fromNetworkLabelValue | quote }}
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists
      {{- if $toNetworkLabel.ports }}
      toPorts:
        - ports:
            {{- range $port := $toNetworkLabel.ports }}
            - port: {{ $port | quote }}
            {{- end }}
      {{- end }}
    {{- end }}
    {{- range .Values.preset.egress.rules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
