variables:
  HELM_CHART_DIRECTORY: "."


include:
  - component: $CI_SERVER_FQDN/to-be-continuous/helm/gitlab-ci-helm@8.2.0
    inputs:
      repos: ""
      publish-on: tag
      publish-strategy: none
      chart-dir: "$HELM_CHART_DIRECTORY"
  - component: $CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@3.15.0
    inputs:
      commit-spec: "conventionalcommits"
      info-on: all
      auto-release-enabled: true


helm-unittest:
  #extends: .helm-base
  stage: test
  image: 
    name: helmunittest/helm-unittest
    entrypoint: [""]
  needs:
    - job: helm-lint
      artifacts: false
  script:
    - helm unittest . --with-subchart=false --output-type JUnit --output-file helmunittest.junit.xml

    - |
      for dir in charts/*; do
        if [ -d "$dir" ] && [ -d "$dir/tests" ]; then
          echo "Running helm unittest for $dir"
          helm unittest "$dir" --with-subchart=false --output-type JUnit --output-file "helmunittest-$(basename "$dir").junit.xml"
        else
          echo "WARN: there seem to be no tests in $dir"
        fi
      done

  artifacts:
    reports:
      junit: helmunittest*.junit.xml
