apiVersion: v2
description: Generic helm Chart for service deployments
name: generic-service
type: application
version: 0.0.1
home: https://github.com/lunarys/generic-helm-chart
dependencies:
  - name: smbstorage
    version: 0.1.0  # must match the version in the subchart...
  - name: externalsecrets
    version: 0.1.0
  - name: networkpolicy
    version: 0.1.0
  - name: longhornstorage
    version: 0.1.0
  - name: localstorage
    version: 0.1.0
  - name: autoscale
    version: 0.1.0
  - name: generic-cronjob
    version: 0.1.0
    alias: cronjob
    condition: cronjob.enabled  # just make the subchart not render anything when disabled
