# -- image pull secret for pulling docker images into a kubernetes cluster. Not needed in our aeb clusters. Only needed for local development.
imagePullSecrets: []

global:
  ingress:
    # -- possibility to use global ingress host for all subcharts
    host: ""

  deployment:
    # -- Globally set policy for auto-restart if an ESecret used in deployments is changed.
    # May be overwritten by the non-global `autoRestartOnSecretChange` setting.
    # @default -- false
    autoRestartOnSecretChange: ""

# -- you can use `"image.registry" + "image.repository"` to specify the docker-image or both with using `"image.name"`.
# set either `"image.registry" + "image.repository"` or `"image.name"`
# @default -- see below
image:
  # -- set either `"image.registry" + "image.repository"` or `"image.name"` 
  registry: "" 
  # -- set either `"image.registry" + "image.repository"` or `"image.name"`  
  repository: ""
  # -- set either `"image.registry" + "image.repository"` or `"image.name"` 
  name: ""
  # -- the docker image tag of the deployed image
  tag: ""
  # -- the pull policy for kubernetes
  pullPolicy: "IfNotPresent"
  # -- override the default command for the container (entrypoint)
  command: []
  # -- override the default arguments for the container
  args: []


# -- possibility to override the desired name of the helm manifest. The default Chart name is automaticly added as prefix
nameOverride: ""
# -- possibility to override the desired name of the helm manifest. This overrides the fullname.
# this value also sets the spring value spring.application.name
fullnameOverride: ""

# -- additional pod annotations
podAnnotations: {}


# -- default resource definition for the app. Have in mind that this has an impact to your jvm heap settings. For more information have a look at the [docs](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
# @default -- see below
resources:
  # -- limits define a threshold when kubernetes intervenes once it sees a violation.
  limits:
    cpu: ""
    memory: ""
  # -- the minimum resource that is available for your pod.
  requests:
    cpu: ""
    memory: ""

# -- definiton of how many pods you want to create.
replicaCount: 1
# -- how many old deployment revision histories you want to keep 
revisionHistoryLimit: 2

# -- possibility to specify a nodeSelector
nodeSelector: {}

# -- possibility to specify tolerations
tolerations: []

# -- possibility to specify affinity
affinity: {}

# -- define privilege and access control settings for a pod. For more information have a look at the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
podSecurityContext: {}

# -- Use `podSecurityContextPreset` if `podSecurityContext` is not set.
usePodSecurityContextPreset: true
# -- Preset for securityContext, will be used if `podSecurityContext` is not set 
# and `usePodSecurityContextPreset` is enabled.
podSecurityContextPreset:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

# -- define privilege and access control settings for a pod. For more information have a look at the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
containerSecurityContext: {}

# -- Use `containerSecurityContextPreset` if `containerSecurityContext` is not set.
useContainerSecurityContextPreset: true
# Preset for securityContext, willbe used if `containerSecurityContext` is not set
# and `useContainerSecurityContextPreset` is enabled.
containerSecurityContextPreset:
  allowPrivilegeEscalation: false
  privileged: false
  runAsNonRoot: true
  # -- Should be enabled if the container supports it.
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL


# -- General ingress settings
ingress:
  enabled: true
  className: ""

  name: ""

  host: ""
  path: /
  pathType: Prefix

  # -- Access control
  accessControl:
    # -- Hostname for external access.
    # @default -- `ingress.host`
    externalHost: ""
    # -- Hostname for internal access.
    # @default -- `ingress.host`
    internalHost: ""
    # -- Whether external should be disabled. Applies the `internalAccessAllowListName` to the ingress.
    externalAccessAllowed: false
    # -- Internal access allowlist name, deployed separately and centrally.
    # Pattern: `{{ namespace }}-{{ name }}@kubernetescrd`.
    internalAccessAllowListName: "traefik-common-internal-access-allowlist@kubernetescrd"

  # -- Custom annotations for the ingress
  annotations: {}


# -- definition for the deployed kubernetes service
# @default -- see below
service:
  enabled: true
  type: ClusterIP
  name: ""
  # -- default port where the ingress routes the traffic to the service
  port: 80
  # -- default port where the service routes the traffic to the pod. Your app has to service anything on this port. It sets the spring value `server.port` to the same value (as an ENV-Var in the configmap)
  targetPort: 8080
  externalIPs: []

# -- Additional Kubernetes services configuration.
# This allows you to define extra services besides the default one.
# Each service can have its own ports and settings.
services:
  example:
    # -- Enable or disable this service.
    enabled: false
    # -- Type of the Kubernetes service (e.g., ClusterIP, NodePort, LoadBalancer).
    type: ClusterIP
    ports:
      example:
        # -- Enable or disable this port.
        enabled: true
        # -- Protocol for the service port (e.g., TCP, UDP).
        protocol: "TCP"
        # -- Port exposed by the service.
        port: 80
        # -- Target port on the pod to route traffic to.
        targetPort: 8080
    # -- List of external IPs for the service.
    externalIPs: []


# -- configuration for the liveness probe. By default, the liveness probe is executed against `{{ .Values.actuator.port }}/{{ .Values.actuator.basePath }}/{{ .Values.actuator.contextPath }}/health/liveness`
# @default -- see below
livenessProbe:
  # -- enables or disables the liveness probe
  enabled: false
  # -- path where the liveness probe checks for the health status of your app. Defaults to spring actuator health endpoint. Helm templating is supported
  path: '/health/liveness'
  # -- port where the liveness probe checks for the health status of your app. Defaults to spring actuator port. Helm templating is supported
  port: "{{ .Values.actuator.port }}"
  # -- initial delay in seconds before the liveness probe starts checking. This is needed because the app needs some time to start up.
  initialDelaySeconds: 10
  # -- period in seconds after which the liveness probe checks again
  periodSeconds: 10
  # -- number of retries before the liveness probe fails and kubernetes restarts the pod
  failureThreshold: 5


# --configuration for the readiness probe. By default, the readiness probe is executed against `{{ .Values.actuator.port }}/{{ .Values.actuator.basePath }}/{{ .Values.actuator.contextPath }}/health/readiness`
# @default -- see below
readinessProbe: 
  # -- enables or disables the readiness probe
  enabled: false
  # -- path where the readiness probe checks for the health status of your app. Defaults to spring actuator health endpoint. Helm templating is supported
  path: '/health/readiness'
  # -- port where the readiness probe checks for the health status of your app. Defaults to spring actuator port. Helm templating is supported
  port: "{{ .Values.actuator.port }}"
  # -- initial delay in seconds before the readiness probe starts checking s
  initialDelaySeconds: 5
  # -- period in seconds after which the readiness probe checks again
  periodSeconds: 10
  # -- number of retries before the readiness probe fails and kubernetes restarts the pod
  failureThreshold: 3


prometheus: 
  # -- enables prometheus scrape config by adding prometheus annotations to the pod. Prometheus metrics are exposed via the spring actuator on the `/prometheus` endpoint
  enabled: true
  

deployment:
  # -- Enable auto-restart of the deployment whenever secrets from 1password are changed.
  # The ESecret operator gracefully restarts the deployment by updating an annotation on the Pod template.
  # @default -- false
  autoRestartOnSecretChange: ""


# -- Possibility to add additional [environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) to your application. 
env: {}
  # if you want pass kubernetes specific values to your app 
  #   KUBE_NAMESPACE: 
  #     valueFrom:
  #       fieldRef:
  #         fieldPath: metadata.namespace  
  # if you want to set additional env variables
  #   DEMO_GREETING: "Hello from the environment"
  #   DEMO_FAREWELL: 
  #     value: "Such a sweet sorrow"



# -- possibility to mount additional secrets, configmaps or volumemounts to your application. Have a look at the values.yaml below for examples.
# @default -- see below
extraConfig:
# extraConfig is used to load Environment Variables from Secrets and ConfigMaps
#
# These Secrets/ConfigMaps are expected to contain Key/Value pairs, such as:
#
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: some-external-configs
# data:
#   POSTGRES_USERNAME: foo
#   POSTGRES_JDBC_URL: jdbc:postgresql://db.example.com:5432/sonar
#
# These vars can then be injected into the environment by uncommenting the following:
#
# extraConfig:
#   configmaps:
#     - some-external-configs

  # -- DEPRECATED: Possibility to add additional [environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) to your application. 
  # Use `env` instead of `extraConfig.env`.
  env: []
   # if you want pass kubernetes specific values to your app 
   # - name: KUBE_NAMESPACE
   #   valueFrom:
   #     fieldRef:
   #       fieldPath: metadata.namespace  
   # if you want to set additional env variables
   # - name: DEMO_GREETING
   #   value: "Hello from the environment"
   # - name: DEMO_FAREWELL
   #   value: "Such a sweet sorrow"

  # -- Possibility to add additional [secrets](https://kubernetes.io/docs/concepts/configuration/secret/) as `envFrom` to your application.
  # Specify the name of the secret that you want to mount. The secret must already exist in the namespace.
  # example:
  # ```	
  # - name: my-secret
  # ```
  secrets: []
  # - name: my-secret # name of the secret that you want to mount, must already exist

  # -- Possibility to add additional [configmaps](https://kubernetes.io/docs/concepts/configuration/configmap/) as `envFrom` to your application.
  # Specify the name of the configmap that you want to mount. The configmap must already exist in the namespace.
  # example:
  # ```
  # - name: my-configmap
  # ```
  configmaps: []
  # - name: my-configmap # name of the configmap that you want to mount, must already exist

  # -- Possibility to add additional [volumemounts](https://kubernetes.io/docs/concepts/storage/volumes/) to your application.
  # Either specify a secretName or a configMap with items or nfs. have a look at the values.yaml below for examples.
  volumeMounts: []
    # --- required config for all variants ---:
    #- name: "" # choose a name of the volume
    #  mountPath: "" # path where you want the volume to be mounted in the container
    #  readOnly: "" # whether the volume is read-only or not
    
    # -- either `secretName` or `configMap` with items or `nfs` ---:

    ### configMap mount -- more information about configmaps [here](https://kubernetes.io/docs/concepts/storage/volumes/#configmap)
    #  configMap: "" # name of the configMap
    #  items: # list of items in the configMap that you want to mount
    #  - key: "" # key in the configMap
    #    path: "" # path where you want the item to be mounted in the container (relative to the mountPath) (name of the file that will be created in the container)
   
    ### secret mount -- more information about secrets [here](https://kubernetes.io/docs/concepts/storage/volumes/#secret)
    #  secretName: "" # name of the secret
    #  items: # list of items in the secret 
    #  - key: "" # key in the secret
    #    path: "" # path where you want the item to be mounted in the container (relative to the mountPath) (name of the file that will be created in the container)
    
    ### nfs mount -- more information about nfs [here](https://kubernetes.io/docs/concepts/storage/volumes/#nfs)
    #  nfs:
    #   server: "" # the address of the NFS server
    #   path: "" # the path on the NFS server
    
    ### emptyDir mount -- more information about emptyDir [here](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
    #  emptyDir: {} # creates an emptyDir volume
    #  # Optional settings for emptyDir:
    #  # sizeLimit: "1Gi" # limit the size of the emptyDir volume
    #  # medium: "Memory" # use tmpfs (RAM) instead of disk storage


# -- Settings for the ServiceAccount for this deployment. These are only applied if there is are any non-default roles (leader election or explicit role bindings).
# @default -- see below
serviceAccount:
  # -- Overwrite the default name of the service account for this backend.
  name: ""
  # -- Whether to create the service account or assume it already exists otherwise.
  create: true
  # -- Additional roles to bind to the service account.
  # List of objects, requiring the `name` of the role and optionally a `kind`, kind defaults to `Role`. Set to `ClusterRole` if required.
  roleBindings: []
   # - name: my-custom-external-role
   #   kind: Role / ClusterRole


#####################################
# -- child charts
#####################################
networkpolicy:
  enabled: false

localstorage:
  enabled: false

smbstorage:
  enabled: false
  mount:
    enabled: true
    path: ""
    # -- SubPath for mounting
    subPath: ""

longhornstorage:
  enabled: true
  # -- Multiple PVC configuration using map with key as volume name
  volumes:
    example:
      # -- Enable/disable this volume.
      enabled: false
      # -- Size of the storage request
      size: ""
      # -- Storage class variant to use (auto-delete, retain, encrypted)
      #variant: ""
      # -- Optional: Custom name for the PVC (defaults to {release-name}-{volume-key}-pvc)
      #name: ""
      # -- Optional: Bind to a specific PersistentVolume by name
      pvName: ""
      # -- Mount configuration for this volume
      mount:
        enabled: true
        path: ""
        subPath: ""
        readonly: false


# -- Settings for externalsecrets integration.
externalsecrets:
  mount:
    # -- Whether to mount the default secret as environment variables.
    env: false
    # -- Path to mount the secret as a file (not implemented).
    # TODO: not implemented
    mountPath: ""
  secrets:
    exampleSecret:
      mount: 
        # -- Whether to mount this secret as environment variables.
        env: false

initCopy:
  enabled: false
  fromVolume: ""
  toVolume: ""
  force: false
