{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name | default (printf "%s-external-secret" .Release.Name) }}
spec:
  target:
    name: {{ coalesce .Values.targetName .Values.name (printf "%s-external-secret" .Release.Name) }}
    deletionPolicy: {{ .Values.deletionPolicy }}
    template:
      type: {{ .Values.secretType }}
      data:
{{- range $key, $val := .Values.fields }}
{{- if (hasKey $val "enabled") | ternary $val.enabled true }}
        {{ $key }}: |-
          {{- if $val.static }}
          {{- $val.static | nindent 10 }}
          {{- else }}
          {{- printf "{{ .%s }}" $key | nindent 10 }}
          {{- end }}
{{- end }}
{{- end }}
  data:
{{- range $key, $val := .Values.fields }}
{{- if (hasKey $val "enabled") | ternary $val.enabled true }}
  {{- if not $val.static }}
    - secretKey: {{ $key }}
      sourceRef:
        storeRef:
          name: {{ $val.storeRefName | default "bitwarden-login" }}
          kind: {{ $val.storeRefKind | default "ClusterSecretStore" }}
      remoteRef:
        key: {{ $val.remoteKey | default $.Values.commonRemoteKey }}
        property: {{ $val.remoteProperty | default $key }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

