{{- if .Values.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name | default (printf "%s-external-secret" .Release.Name) }}
spec:
  target:
    name: {{ coalesce .Values.targetName .Values.name (printf "%s-external-secret" .Release.Name) }}
    deletionPolicy: {{ .Values.deletionPolicy }}
    template:
      type: {{ .Values.secretType }}
      data:
{{- range $key, $val := .Values.fields }}
{{- if or (kindIs "string" $val) ((hasKey $val "enabled") | ternary $val.enabled true) }}
        {{ $key }}: |-
          {{- if kindIs "string" $val }}
          {{ $val }}
          {{- else if $val.static }}
          {{ $val.static }}
          {{- else }}
          {{ printf "{{ .%s }}" $key }}
          {{- end }}
{{- end }}
{{- end }}
  data:
{{- range $key, $val := .Values.fields }}
{{- if or (kindIs "string" $val) ((hasKey $val "enabled") | ternary $val.enabled true) }}
  {{- if not (or (kindIs "string" $val) $val.static) }}
    - secretKey: {{ $key }}
      sourceRef:
        storeRef:
          name: {{ $val.storeRefName | default "bitwarden-login" }}
          kind: {{ $val.storeRefKind | default "ClusterSecretStore" }}
      remoteRef:
        key: {{ $val.remoteKey | default $.Values.commonRemoteKey }}
        property: {{ $val.remoteProperty | default $key }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

