{{- if .Values.enabled }}
{{- if .Values.variant }}
  {{- if and (ne .Values.variant "pv") (ne .Values.variant "storageclass") }}
    {{ fail "No known variant selected: Available are pv, storageclass" }}
  {{- end }}
{{- else }}
  {{- fail "Variant is unset" }}
{{- end }}
{{- end }}
