{{- if .Values.enabled }}
{{- range $name, $volume := .Values.volumes }}
{{- if and (or (not (hasKey $volume "enabled")) $volume.enabled) (hasKey $volume "externalsecret") (or (not (hasKey $volume.externalsecret "enabled")) $volume.externalsecret.enabled) }}
---
{{- $volumeExternalSecret := $volume.externalsecret }}
{{- if not (hasKey $volumeExternalSecret "fields") }}
{{- $volumeExternalSecret = mustMerge $volumeExternalSecret (dict "fields" $.Values.externalsecretFieldDefault) }}
{{- end }}
{{- include "external-secrets.secret" (set (dict "values" (mustMerge $volumeExternalSecret $.Values.externalsecrets)) "name" (include "smbstorage.secretName" (dict "volume" $volume "volumeName" $name "Release" $.Release))) }}
{{- end }}
{{- end }}
{{- end }}
