{{- if and .Values.enabled .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s-pvc-smb" .Release.Name) | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.mount.capacity }}
  resources:
    requests:
      storage: {{ .Values.mount.capacity }}
  {{- end }}
  {{- if eq .Values.variant "pv" }}
    {{- if and (not .Values.pv.enabled) (not .Values.pv.name) }}
      {{- fail "pv.name for external pv is not set" }}
    {{- end }}
  # empty to disable dynamic provisioning via storageclass
  volumeName: {{ .Values.pv.name | default (printf "%s-pv-smb" .Release.Name) | quote }}
  storageClassName: ""
  {{- else if eq .Values.variant "storageclass" }}
    {{- if and (not .Values.storageclass.enabled) (not .Values.storageclass.name) }}
      {{- fail "storageclass.name for external StorageClass is not set" }}
    {{- end }}
  storageClassName: {{ .Values.storageclass.name | default (printf "%s-storageclass-%s" .Release.Name .Values.smb.share) | quote }}
  {{- else }}
    {{- fail "Variant is neither pv nor storageclass" }}
  {{- end }}
{{ end }}

