{{- if .Values.enabled }}
{{- range $name, $volume := .Values.volumes }}
{{- if (or (not (hasKey $volume "enabled")) $volume.enabled) }}
{{- $pvcEnabled := true }}
{{- if hasKey $volume "pvc" }}{{ $pvcEnabled = (or (not (hasKey $volume.pvc "enabled")) $volume.pvc.enabled) }}{{ end }}
{{- if $pvcEnabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smbstorage.pvcName" (dict "volume" $volume "volumeName" $name "Release" $.Release) | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- $mount := $volume.mount | default dict }}
  {{- $capacity := coalesce $mount.capacity $volume.smb.capacity }}
  resources:
    requests:
      storage: {{ $capacity | required (printf "PVC capacity is required: either mount.capacity or smb.capacity must be specified for volume '%s'" $name) }}
  {{- $pvEnabled := true }}
  {{- if hasKey $volume "pv" }}{{ $pvEnabled = $volume.pv.enabled }}{{ end }}
  {{- if and (not $pvEnabled) (not (and $volume.pv $volume.pv.name)) }}
    {{- fail "pv.name for external pv is not set" }}
  {{- end }}
  # empty to disable dynamic provisioning via storageclass
  volumeName: {{ include "smbstorage.pvName" (dict "volume" $volume "volumeName" $name "Release" $.Release) | quote }}
  storageClassName: ""
{{- end }}
{{- end }}
{{- end }}
{{- end }}

