{{- if .Values.enabled }}
{{- range $name, $volume := .Values.volumes }}
{{- if and (or (not (hasKey $volume "enabled")) $volume.enabled) (hasKey $volume "secret") $volume.secret.enabled }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "smbstorage.secretName" (dict "volume" $volume "volumeName" $name "Release" $.Release) | quote }}
  {{- $secretNamespace := $.Release.Namespace }}
  {{- if $volume.secret.namespace }}{{ $secretNamespace = $volume.secret.namespace }}{{ end }}
  namespace: {{ $secretNamespace | quote }}
stringData:
  username: {{ $volume.secret.user | quote }}
  password: {{ $volume.secret.password | quote }}
  domain: {{ $volume.secret.domain | default "WORKGROUP" | quote }}
{{- end }}
{{- end }}
{{- end }}
