apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name | default (printf "%s-longhorn-pvc" .Release.Name) }}
spec:
  accessModes:
    - {{ .Values.accessMode }}
  storageClassName: {{ index .Values.storageClassVariants .Values.variant | required "storageClassVariants must contain the variant" }}
  {{- if .Values.pvName }}
  volumeName: {{ .Values.pvName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.size | required "size must be set" }}
