apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "ju-common.labels" . | nindent 4 }}
  name: {{ include "ju-common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ju-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "ju-common.annotations" . | nindent 8 }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'todo'
        prometheus.io/port: 'todo'
        {{- else }}
        prometheus.io/scrape: 'false'
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ju-common.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "ju-common.podSecurityContext" . | nindent 8 }}
      {{- if include "ju-backend.isCustomizedServiceAccount" . }}
      serviceAccountName: {{ include "ju-backend.serviceAccountName" . | quote }}
      {{- end }}
      containers:
        - name: {{ include "ju-common.fullname" . }}
          image: {{ include "ju-common.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{- toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- if and .limits (or .limits.memory .limits.cpu) }}
            limits:
              {{- if .limits.memory }}
              memory: {{ .limits.memory }}
              {{- end }}
              {{- if .limits.cpu }}
              cpu: {{ .limits.cpu }}
              {{- end }}
            {{- end }}
            {{- if and .requests (or .requests.memory .requests.cpu) }}
            requests:
              {{- if .requests.memory }}
              memory: {{ .requests.memory }}
              {{- end }}
              {{- if .requests.cpu }}
              cpu: {{ .requests.cpu }}
              {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            {{- include "ju-common.containerSecurityContext" . | nindent 12 }}
          #readiness & liveness
          {{- if .Values.livenessProbe.enabled }}
          {{- if .Values.livenessProbe.override }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.override | nindent 12 }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /{{  trimAll "/" (tpl .Values.livenessProbe.path .) }}
              port: {{ tpl .Values.livenessProbe.port . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          {{- if .Values.readinessProbe.override }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.override | nindent 12 }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /{{  trimAll "/" (tpl .Values.readinessProbe.path .) }}
              port: {{ tpl .Values.readinessProbe.port . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: default
              protocol: {{ .Values.service.protocol }}
            {{- range $name, $service := .Values.services }}
              {{- if $service.enabled }}
                {{- range $portName, $port := $service.ports }}
                  {{- if or (not (hasKey $port "enabled")) $port.enabled }}
            - containerPort: {{ $port.targetPort }}
              name: {{ printf "%s-%s" $name $portName }}
              protocol: {{ $port.protocol | default "TCP" }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          #config values that comes from the configmap 
          envFrom:
            {{- with .Values.externalsecrets }}
            {{- if .enabled }}
            {{- if .mount.env }}
            - secretRef:
                name: {{ default (printf "%s-external-secret" $.Release.Name) .name }}
            {{- end }}
            {{- range $key, $value := .secrets }}
            {{- if and $value.enabled (hasKey $value "mount") $value.mount.env }}
            - secretRef:
                name: {{ default $key $value.name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraConfig.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.extraConfig.configmaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          {{- if or .Values.env .Values.extraConfig.env }}
          env:
            {{- if .Values.env }}
            # settings from 'env'
            {{- range $name, $value := .Values.env }}
            - name: {{ default $name | quote }}
              {{- if kindIs "string" $value }}
              value: {{ $value | quote }}
              {{- else }}
              {{- omit $value "name" | toYaml | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraConfig.env }}
            # Deprecated variable settings from 'extraConfig.env'
              {{- .Values.extraConfig.env | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- range .Values.extraConfig.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
            {{- if and .Values.smbstorage.enabled .Values.smbstorage.mount.enabled }}
            - name: smb
              mountPath: {{ .Values.smbstorage.mount.path | required "smbstorage.mount.path is required" }}
              readOnly: {{ .Values.smbstorage.mount.readonly | default false }}
              {{- if .Values.smbstorage.mount.subPath }}
              subPath: {{ .Values.smbstorage.mount.subPath }}
              {{- end }}
            {{- end }}
            {{- if .Values.longhornstorage.enabled }}
            {{- range $volumeName, $volume := .Values.longhornstorage.volumes }}
            {{- if and (or (not (hasKey $volume "enabled")) $volume.enabled) $volume.mount $volume.mount.path (or (not (hasKey $volume.mount "enabled")) $volume.mount.enabled) }}
            - name: {{ printf "longhorn-%s" $volumeName }}
              mountPath: {{ $volume.mount.path | required (printf "longhornstorage.volumes.%s.mount.path is required" $volumeName) }}
              readOnly: {{ $volume.mount.readonly | default false }}
              {{- if $volume.mount.subPath }}
              subPath: {{ $volume.mount.subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
      volumes:
        {{- range .Values.extraConfig.volumeMounts }}
        - name: {{ .name }}
          {{- if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            {{- if .hostPath.type }}
            type: {{ .hostPath.type | quote }}
            {{- end }}
          {{- else if or .configMap .secretName }}
          {{- if .secretName }}
          secret:
            secretName: {{ .secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap }}
          {{- end }}
            {{- if .items }}
            items:
              {{- range $v := .items }}
              - key: {{ $v.key }}
                path: {{ $v.path }}
              {{- end }}
            {{- end }}
          {{- else if .nfs }}
          nfs:
            server: {{ .nfs.server }}
            path: {{ .nfs.path }}
          {{- else if .emptyDir }}
          emptyDir:
            {{- if .sizeLimit }}
            sizeLimit: {{ .sizeLimit }}
            {{- end }}
            {{- if .medium }}
            medium: {{ .medium }}
            {{- end }}
          {{- else }}
            {{- fail "Neither hostPath, secretName, configMap, nfs nor emptyDir is defined as volume " -}}
          {{- end }}
        {{- end }}
        {{- if and .Values.smbstorage.enabled .Values.smbstorage.mount.enabled }}
        - name: smb
          persistentVolumeClaim:
            claimName: {{ .Values.smbstorage.pvc.name | default (printf "%s-pvc-smb" .Release.Name) }}
        {{- end }}
        {{- if .Values.longhornstorage.enabled }}
        {{- range $volumeName, $volume := .Values.longhornstorage.volumes }}
        {{- if and (or (not (hasKey $volume "enabled")) $volume.enabled) $volume.mount $volume.mount.path (or (not (hasKey $volume.mount "enabled")) $volume.mount.enabled) }}
        - name: {{ printf "longhorn-%s" $volumeName }}
          persistentVolumeClaim:
            claimName: {{ $volume.name | default (printf "%s-%s-pvc" $.Release.Name $volumeName) }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initCopy.enabled }}
      initContainers:
        - name: copy-volume-data
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
            {{- if not .Values.initCopy.force }}
              # Exclude lost+found from the check
              if [ -z "$(ls -A /to | grep -v '^lost+found$')" ]; then
                echo "Target directory /to is empty, proceeding with copy."
                cp -a /from/. /to/.
                echo "Copy completed."
              else
                echo "Target directory /to is not empty skipping copy."
              fi
            {{- else }}
              cp -a /from/. /to/.
            {{- end }}
          volumeMounts:
            - name: {{ .Values.initCopy.fromVolume | required "initCopy.fromVolume must be set" }}
              mountPath: /from
              readOnly: true
            - name: {{ .Values.initCopy.toVolume | required "initCopy.toVolume must be set" }}
              mountPath: /to
              readOnly: false
      {{- end }}
