apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "ju-common.labels" . | nindent 4 }}
  name: {{ include "ju-common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ju-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "ju-common.annotations" . | nindent 8 }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'todo'
        prometheus.io/port: 'todo'
        {{- else }}
        prometheus.io/scrape: 'false'
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ju-common.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if include "ju-backend.isCustomizedServiceAccount" . }}
      serviceAccountName: {{ include "ju-backend.serviceAccountName" . | quote }}
      {{- end }}
      containers:
        - name: {{ include "ju-common.fullname" . }}
          image: {{ include "ju-common.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{- toYaml .Values.image.command | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{- toYaml .Values.image.args | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          #readiness & liveness
          {{- if .Values.livenessProbe.enabled }}
          {{- if .Values.livenessProbe.override }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.override | nindent 12 }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /{{  trimAll "/" (tpl .Values.livenessProbe.path .) }}
              port: {{ tpl .Values.livenessProbe.port . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          {{- if .Values.readinessProbe.override }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.override | nindent 12 }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /{{  trimAll "/" (tpl .Values.readinessProbe.path .) }}
              port: {{ tpl .Values.readinessProbe.port . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          #config values that comes from the configmap 
          envFrom:
            {{- range .Values.extraConfig.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.extraConfig.configmaps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
          {{- if .Values.extraConfig.env }}
          env:
            {{- if .Values.extraConfig.env }}
              {{- .Values.extraConfig.env | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          #external mounted Spring Boot Properties
          {{- if .Values.extraConfig.volumeMounts }}
          volumeMounts:
            {{- range .Values.extraConfig.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly | default false }}
            {{- end }}
          {{- end }}
      {{- if .Values.extraConfig.volumeMounts }}
      volumes:
        {{- range .Values.extraConfig.volumeMounts }}
        - name: {{ .name }}
          {{- if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            {{- if .hostPath.type }}
            type: {{ .hostPath.type | quote }}
            {{- end }}
          {{- else if or .configMap .secretName }}
          {{- if .secretName }}
          secret:
            secretName: {{ .secretName }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap }}
          {{- end }}
            {{- if .items }}
            items:
              {{- range $v := .items }}
              - key: {{ $v.key }}
                path: {{ $v.path }}
              {{- end }}
            {{- end }}
          {{- else if .nfs }}
          nfs:
            server: {{ .nfs.server }}
            path: {{ .nfs.path }}
          {{- else }}
            {{- fail "Neither hostPath, secretName, configMap nor nfs is defined as volume " -}}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
