{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ju-common.ingressName" . }}
  annotations:
    {{- include "ju-common.ingress.middlewares" . | indent 4 }}
    {{- with .Values.ingress.annotations -}}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "ju-common.ingress.internalHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "ju-common.serviceName" . }}
                port:
                  number: {{ .Values.service.port }}
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
    {{- if and .Values.ingress.accessControl.externalAccessAllowed (ne (include "ju-common.ingress.externalHost" .) (include "ju-common.ingress.internalHost" .)) }}
    - host: {{ include "ju-common.ingress.externalHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "ju-common.serviceName" . }}
                port:
                  number: {{ .Values.service.port }}
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
    {{- end }}
{{- end }}
