{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "ju-common.serviceName" $ }}-{{ $name }}
  labels:
    {{- include "ju-common.labels" $ | nindent 4 }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    {{- range $portName, $port := $service.ports }}
    {{- if or (not (hasKey $port "enabled")) $port.enabled }}
    - name: {{ $portName }}
      protocol: {{ $port.protocol | default "TCP" }}
      port: {{ $port.port | required "port for a service in services is missing" }}
      targetPort: {{ $port.targetPort | default $port.port }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "ju-common.selectorLabels" $ | nindent 4 }}
  {{- if $service.externalIPs }}
  externalIPs:
    {{- range $ip := $service.externalIPs }}
    - {{ $ip }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
