{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "ju-common.serviceName" . }}
  labels:
    {{- include "ju-common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: default-service-endpoint
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "ju-common.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range $ip := .Values.service.externalIPs }}
    - {{ $ip }}
    {{- end }}
  {{- end }}
{{- end }}
