{{- if .Values.enabled }}
{{- range $name, $volume := .Values.volumes }}
{{- if or (not (hasKey $volume "enabled")) $volume.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name | default (printf "%s-%s-pvc" $.Release.Name $name) }}
spec:
  accessModes:
    - {{ $volume.accessMode | default $.Values.defaultAccessMode }}
  storageClassName: {{ index $.Values.storageClassVariants ($volume.variant | default $.Values.defaultVariant) | required "storageClassVariants must contain the variant" }}
  {{- if $volume.pvName }}
  volumeName: {{ $volume.pvName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $volume.size | required (printf "volumes.%s.size must be set" $name) }}
{{- end }}
{{- end }}
{{- end }}
