{{- if and .Values.create.pv .Values.variant.pv }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name | default (printf "%s-pv-smb-%s" .Release.Name .Chart.Name) | quote }}
  {{- if .Values.pv.static }}
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  {{- end }}
spec:
  {{- if .Values.smb.capacity }}
  capacity:
    storage: 10Gi
  {{- end }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete  # available values: Delete, Retain
  # empty to disable dynamic provisioning via storageclass
  storageClassName: ""
  {{- if .Values.create.pvc }}
  claimRef:
    name: {{ .Values.pvc.name | default (printf "%s-pvc-smb-%s" .Release.Name .Chart.Name) | quote }}
    namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  mountOptions:
    - dir_mode={{ .Values.mount.dir_mode | default "0777" }}
    - file_mode={{ .Values.mount.file_mode | default "0777" }}
    - uid={{ .Values.mount.uid | default "1001" }}
    - gid={{ .Values.mount.gid | default "1001" }}
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "{{ .Values.smb.host }}/{{ .Values.smb.share }}##"
    volumeAttributes:
      source: "//{{ .Values.smb.host }}/{{ .Values.smb.share }}"
    nodeStageSecretRef:
      name: "{{ .Values.smb.secret.name | default "smb-creds" }}"
      namespace: "{{ .Values.smb.secret.namespace | default .Release.Namespace }}"
{{- end }}

