{{- if and .Values.enabled (eq .Values.variant "pv") .Values.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name | default (printf "%s-pv-smb" .Release.Name) | quote }}
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  {{- if .Values.smb.capacity }}
  capacity:
    storage: {{ .Values.smb.capacity }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete  # available values: Delete, Retain
  # empty to disable dynamic provisioning via storageclass
  storageClassName: ""
  {{- if .Values.pvc.enabled }}
  claimRef:
    name: {{ .Values.pvc.name | default (printf "%s-pvc-smb" .Release.Name) | quote }}
    namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  mountOptions:
    - dir_mode={{ .Values.mount.dir_mode }}
    - file_mode={{ .Values.mount.file_mode }}
    - uid={{ .Values.mount.uid }}
    - gid={{ .Values.mount.gid }}
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
    {{- range .Values.mount.extraOptions }}
    - {{ . }}
    {{- end }}
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: "{{ .Values.smb.host }}/{{ .Values.smb.share }}##"
    volumeAttributes:
      source: "//{{ .Values.smb.host }}/{{ .Values.smb.share }}"
    nodeStageSecretRef:
      {{- if index .Values "external-secrets" "enabled" }}
      name: {{ index .Values "external-secrets" "name" | default "smb-creds" }}
      {{- else }}
      name: {{ .Values.smb.secret.name | default "smb-creds" }}
      {{- end }}
      namespace: "{{ .Values.smb.secret.namespace | default .Release.Namespace }}"
{{- end }}

