{{- if .Values.create.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default "pvc-smb" | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.mount.capacity }}
  resources:
    requests:
      storage: {{ .Values.mount.capacity }}
  {{- end }}
  {{- if .Values.variant.pv }}
    {{- if and (not .Values.create.pv) (not .Values.pv.name) }}
      {{- fail "pv.name for external pv is not set" }}
    {{- end }}
  volumeName: {{ .Values.pv.name | default "pv-smb" | quote }}
  # empty to disable dynamic provisioning via storageclass
  storageClassName: ""
  {{- else if .Values.variant.storageclass }}
    {{- if and (not .Values.create.storageclass) (not .Values.storageclass.name) }}
      {{- fail "storageclass.name for external StorageClass is not set" }}
    {{- end }}
  storageClassName: {{ .Values.storageclass.name | default (printf "%s-storageclass-%s" .Release.Name .Values.smb.share) | quote }}
  {{- else }}
    {{- fail "Variant is neither pv nor storageclass" }}
  {{- end }}
{{ end }}

