{{- if .Values.create.secret }}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.smb.secret.name | quote }}
stringData:
  username: {{ .Values.smb.secret.user | quote }}
  password: {{ .Values.smb.secret.password | quote }}
  domain: {{ .Values.smb.secret.domain | quote }}
{{- end }}
