global:
  ingress:
    host: ""

nameOverride: "custom-ingress"

# -- General ingress settings
ingress:
  enabled: true
  className: ""      # Set to your ingress class if needed, e.g. "traefik"
  host: ""           # Set to your desired host, e.g. "example.com"

  # -- Access control
  accessControl:
    # -- Hostname for external access.
    # @default -- `ingress.host`
    externalHost: ""
    # -- Hostname for internal access.
    # @default -- `ingress.host`
    internalHost: ""
    # -- Whether external should be disabled. Applies the `internalAccessAllowListName` to the ingress.
    externalAccessAllowed: false
    # -- Internal access allowlist name, deployed separately and centrally.
    # Pattern: `{{ namespace }}-{{ name }}@kubernetescrd`.
    internalAccessAllowListName: "settings-traefik-internal-access-allowlist"

  # -- Custom annotations for the ingress
  annotations: {}

  # -- Additional middleware for the ingress
  middleware:
    enabled: false
    name: "custom-middleware"
    ipAllowList:
      sourceRange:
        - 10.0.0.0/22  # Default allowed IP ranges
        - 192.168.1.7
