global:
  ingress:
    host: ""

nameOverride: "custom-ingress"

# -- General ingress settings
ingress:
  enabled: true
  className: ""

  host: ""
  path: /
  pathType: Prefix

  # -- Access control
  accessControl:
    # -- Hostname for external access.
    # @default -- `ingress.host`
    externalHost: ""
    # -- Hostname for internal access.
    # @default -- `ingress.host`
    internalHost: ""
    # -- Whether external should be disabled. Applies the `internalAccessAllowListName` to the ingress.
    externalAccessAllowed: false
    # -- Internal access allowlist name, deployed separately and centrally.
    # Pattern: `{{ namespace }}-{{ name }}@kubernetescrd`.
    internalAccessAllowListName: "settings-traefik-internal-access-allowlist"

  # -- Custom annotations for the ingress
  annotations: {}

  # -- Additional middleware for the ingress.
  # TODO: Not done implementing!
  middleware:
    enabled: false
    name: "custom-middleware"
    ipAllowList:
      sourceRange:
        - 10.0.0.0/22  # Default allowed IP ranges
        - 192.168.1.7


# -- Configuration for the service that this ingress will route to
service:
  name: "{{ fail \"service.name is required\" }}"
  port: "{{ fail \"service.port is required\" }}"

