{{- if and .Values.serviceAccount.create (include "ju-backend.isCustomizedServiceAccount" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ju-backend.serviceAccountName" . }}
automountServiceAccountToken: true
{{- end }}