# variants:
#   - storageclass: storageclass + pvc (static: false)
#   - pv: pv + pvc (static: true)
#   - pvc with existing (external) pv? -> maybe storageclass is better?
#   - pvc with existing (external) storageclass
#   - ephemeral? https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

# TODO: capacity is required

# -- Enable or disable the chart
enabled: true

# -- Provisioning variant: "pv" (static, default) or "storageclass" (dynamic)
# See https://github.com/kubernetes-csi/csi-driver-smb/blob/master/deploy/example/e2e_usage.md
# TODO: storageclass is not yet fully implemented
variant: pv

pv:
  enabled: true
  # -- Name of the PersistentVolume (if using static provisioning)
  name: ""

pvc:
  enabled: true
  # -- Name of the PersistentVolumeClaim
  name: ""

# -- Only relevant for dynamic provisioning via StorageClass (variant: "storageclass")
storageclass:
  enabled: true
  # -- Name of the StorageClass
  name: ""

# -- Use the external-secrets helper chart to create the SMB credentials Secret
external-secrets:
  enabled: false
  name: "smb-creds"
  commonRemoteKey: ""
  fields:
    username:
      storeRefName: bitwarden-login
      remoteProperty: username
    password:
      storeRefName: bitwarden-login
      remoteProperty: password
    domain:
      static: "WORKGROUP"


# -- Settings for the smb share
smb:
  # -- SMB server hostname or IP
  host: "erolas.elda"
  # -- SMB share name
  share: "test"
  # -- Alternatively, specify the full SMB source URI
  #source: "//erolas.elda/test"
  # -- Total available capacity for the share (e.g., 10Gi)
  capacity: "10Gi"
  secret:
    enabled: false
    # -- Name of the Secret containing SMB credentials (if using existing Secret)
    name: "smb-creds"
    # -- Namespace for the Secret
    namespace: "smb-test"
    # -- SMB username (if creating Secret)
    user:
    # -- SMB password (if creating Secret)
    password:
    # -- SMB domain (optional)
    domain: "WORKGROUP"


# -- Mount options for the SMB share (need to be implemented by the wrapper chart)
mount:
  # -- Directory mode for mounted volume
  dir_mode: "0777"
  # -- File mode for mounted volume
  file_mode: "0777"
  # -- UID for mounted volume
  uid: "1001"
  # -- GID for mounted volume
  gid: "1001"
  # -- SubPath for mounting
  subPath: ""
  # -- Mount as read-only
  readonly: false
  # -- Requested capacity for the PVC
  capacity: "10Gi"
  # -- Additional mount options
  extraOptions: []
