{{- define "ju.ingress" }}
{{-   if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}
  annotations:
    {{- include "ju.ingress.middlewares" . | nindent 4 }}
    {{- with .Values.ingress.annotations -}}
    {{-   toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "ju.ingress.internalHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ tpl .Values.service.name . }}
                port:
                  number: {{ tpl (toString .Values.service.port) . | int }}
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
    {{- if and .Values.ingress.accessControl.externalAccessAllowed (ne (include "ju.ingress.externalHost" .) (include "ju.ingress.internalHost" .)) }}
    - host: {{ include "ju.ingress.externalHost" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ tpl .Values.service.name . }}
                port:
                  number: {{ tpl (toString .Values.service.port) . | int }}
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
    {{- end }}
{{-   end }}
{{- end }}

{{ template "ju.ingress" . }}
