{{- if .Values.enabled }}
  {{- if include "external-secrets.hasEnabledFields" . }}
    {{- include "external-secrets.secret" (set (dict "values" .Values) "name" (default (printf "%s-external-secret" .Release.Name) .Values.name)) }}
  {{- end }}
  
  {{- if .Values.secrets }}
    {{- range $key, $value := .Values.secrets }}
      {{- if or (not (hasKey $value "enabled")) $value.enabled }}
        {{- include "external-secrets.secret" (set (dict "values" (mustMerge (deepCopy $value) $.Values)) "name" (default $key $value.name)) }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
